name: Build and deploy Node.js app to Azure Web App

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v2

    - name: Set up Node.js version
      uses: actions/setup-node@v2
      with:
        node-version: '20.x'

    - name: 'Install dependencies'
      run: |
        cd backend
        npm install

    - name: 'Build and deploy'
      env:
        AZURE_WEBAPP_NAME: prograweb  # Cambia esto por el nombre de tu App Service
        AZURE_WEBAPP_PACKAGE_PATH: backend     # Asegúrate de que apunte a la carpeta correcta
      run: |
        zip -r myapp.zip .
        npx azure-webapps-deploy@v2 --package myapp.zip --app-name $AZURE_WEBAPP_NAME --slot-name 'production'
